"""
report_builder.py
Builds a downloadable PDF summary of a case analysis.
"""

import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="H1Custom", fontSize=18, leading=22, spaceAfter=10,
                               textColor=colors.HexColor("#1c2b45"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="H2Custom", fontSize=13, leading=16, spaceBefore=14, spaceAfter=6,
                               textColor=colors.HexColor("#9a2b2b"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="BodyCustom", fontSize=10, leading=14, spaceAfter=6))
    styles.add(ParagraphStyle(name="Meta", fontSize=9, leading=12, textColor=colors.grey))
    return styles


def build_case_report(case_doc, structured_facts: dict, analysis: dict, file_name: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    styles = _styles()
    story = []

    story.append(Paragraph("CaseCounsel AI — Case Analysis Report", styles["H1Custom"]))
    story.append(Paragraph(f"Source document: {file_name} &nbsp;|&nbsp; Type: {case_doc.doc_type}", styles["Meta"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Case Overview", styles["H2Custom"]))
    overview_rows = [
        ["FIR Number", case_doc.fir_number or "Not detected"],
        ["Police Station", case_doc.police_station or "Not detected"],
        ["Sections Cited", ", ".join(case_doc.sections_cited) or "None detected"],
        ["Complainant", structured_facts.get("complainant") or "N/A"],
        ["Accused", ", ".join(structured_facts.get("accused") or []) or "N/A"],
        ["Date of Incident", structured_facts.get("date_of_incident") or "N/A"],
        ["Investigating Officer", structured_facts.get("investigating_officer") or "N/A"],
    ]
    tbl = Table(overview_rows, colWidths=[4.5*cm, 11*cm])
    tbl.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e0d5")),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Allegation Summary", styles["H2Custom"]))
    story.append(Paragraph(structured_facts.get("allegation_summary") or "Not available", styles["BodyCustom"]))

    story.append(Paragraph("Applicable Law", styles["H2Custom"]))
    story.append(Paragraph(analysis.get("applicable_law_summary") or "N/A", styles["BodyCustom"]))

    story.append(PageBreak())

    story.append(Paragraph("Prosecution Points", styles["H2Custom"]))
    for p in analysis.get("prosecution_points", []):
        text = f"<b>[{p.get('strength', '').upper()}]</b> {p.get('point')} <i>(Grounded in: {p.get('grounded_in')})</i>"
        story.append(Paragraph(text, styles["BodyCustom"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Cross-Examination Points", styles["H2Custom"]))
    for p in analysis.get("cross_examination_points", []):
        text = (f"<b>Target: {p.get('target')}</b> — {p.get('point')}<br/>"
                f"<i>Suggested question: \"{p.get('suggested_question')}\"</i><br/>"
                f"<font size=8 color='grey'>Grounded in: {p.get('grounded_in')}</font>")
        story.append(Paragraph(text, styles["BodyCustom"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Procedural Compliance Checks", styles["H2Custom"]))
    for c in analysis.get("procedural_checks", []):
        text = f"<b>[{c.get('status', '').upper()}]</b> {c.get('check')} — {c.get('note', '')}"
        story.append(Paragraph(text, styles["BodyCustom"]))

    if analysis.get("gaps_in_retrieved_context"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("Gaps Flagged — Verify Manually", styles["H2Custom"]))
        for gap in analysis["gaps_in_retrieved_context"]:
            story.append(Paragraph(f"• {gap}", styles["BodyCustom"]))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "Generated by CaseCounsel AI — a research and drafting aid for licensed advocates. "
        "Not a substitute for independent legal verification.",
        styles["Meta"],
    ))

    doc.build(story)
    return buf.getvalue()
